model_params :
  in_channels: 3
  out_channels: 2
  n_blocks: 4
  start_filters: 32
  activation: "relu"
  normalization: "batch"
  conv_mode: "same"
  dim: 2
training_params :
  lr: 0.001
  epochs: 30